{
 "username": null,
  "avatar_url": null,
  "content": "",
  "embeds": [
    {
      "author": {
        "name": "",
        "icon_url": ""
      },
      "title": "",
      "url": "",
      "color": ,
      "fields": [
        {
          "name": "",
          "value": ""
        }
      ],
      "thumbnail": {
        "url": ""
      },
      "image": {
        "url": ""
      },
      "footer": {
        "text": "",
        "icon_url": ""
      }
    }
  ]
}
